package org.ivela.offline.domain;

import java.util.Date;

public class ChallengeItems {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.xml
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String xml;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long course;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long discipline;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long unit;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.timestamp
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Date timestamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.dependency
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long dependency;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge_items.weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer weight;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.id
     *
     * @return the value of challenge_items.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.id
     *
     * @param id the value for challenge_items.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.name
     *
     * @return the value of challenge_items.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.name
     *
     * @param name the value for challenge_items.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.xml
     *
     * @return the value of challenge_items.xml
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getXml() {
        return xml;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.xml
     *
     * @param xml the value for challenge_items.xml
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setXml(String xml) {
        this.xml = xml;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.course
     *
     * @return the value of challenge_items.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getCourse() {
        return course;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.course
     *
     * @param course the value for challenge_items.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setCourse(Long course) {
        this.course = course;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.discipline
     *
     * @return the value of challenge_items.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getDiscipline() {
        return discipline;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.discipline
     *
     * @param discipline the value for challenge_items.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDiscipline(Long discipline) {
        this.discipline = discipline;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.unit
     *
     * @return the value of challenge_items.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getUnit() {
        return unit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.unit
     *
     * @param unit the value for challenge_items.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUnit(Long unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.timestamp
     *
     * @return the value of challenge_items.timestamp
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.timestamp
     *
     * @param timestamp the value for challenge_items.timestamp
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.dependency
     *
     * @return the value of challenge_items.dependency
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getDependency() {
        return dependency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.dependency
     *
     * @param dependency the value for challenge_items.dependency
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDependency(Long dependency) {
        this.dependency = dependency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge_items.weight
     *
     * @return the value of challenge_items.weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge_items.weight
     *
     * @param weight the value for challenge_items.weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}