package org.ivela.offline.domain;

public class Discipline {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column discipline.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column discipline.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long course;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column discipline.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column discipline.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String tag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column discipline.id
     *
     * @return the value of discipline.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column discipline.id
     *
     * @param id the value for discipline.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column discipline.course
     *
     * @return the value of discipline.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getCourse() {
        return course;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column discipline.course
     *
     * @param course the value for discipline.course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setCourse(Long course) {
        this.course = course;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column discipline.name
     *
     * @return the value of discipline.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column discipline.name
     *
     * @param name the value for discipline.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column discipline.tag
     *
     * @return the value of discipline.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column discipline.tag
     *
     * @param tag the value for discipline.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}