package org.ivela.offline.domain;

public class FinishedUnitContent {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column finished_unit_content.id
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column finished_unit_content.system_user
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	private Long systemUser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column finished_unit_content.course
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	private Long course;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column finished_unit_content.unit_content
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	private Long unitContent;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column finished_unit_content.id
	 * @return  the value of finished_unit_content.id
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column finished_unit_content.id
	 * @param id  the value for finished_unit_content.id
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column finished_unit_content.system_user
	 * @return  the value of finished_unit_content.system_user
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public Long getSystemUser() {
		return systemUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column finished_unit_content.system_user
	 * @param systemUser  the value for finished_unit_content.system_user
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public void setSystemUser(Long systemUser) {
		this.systemUser = systemUser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column finished_unit_content.course
	 * @return  the value of finished_unit_content.course
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public Long getCourse() {
		return course;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column finished_unit_content.course
	 * @param course  the value for finished_unit_content.course
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public void setCourse(Long course) {
		this.course = course;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column finished_unit_content.unit_content
	 * @return  the value of finished_unit_content.unit_content
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public Long getUnitContent() {
		return unitContent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column finished_unit_content.unit_content
	 * @param unitContent  the value for finished_unit_content.unit_content
	 * @ibatorgenerated  Thu Apr 15 14:20:41 BRT 2010
	 */
	public void setUnitContent(Long unitContent) {
		this.unitContent = unitContent;
	}
}