package org.ivela.offline.domain;
import java.util.Date;

public class SystemUser {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.email
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.social_number
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String socialNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.username
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.password
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Boolean enabled;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.profile
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long profile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.last_unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long lastUnitContent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.created_at
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Date createdAt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column system_user.authentication
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long authentication;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.id
     *
     * @return the value of system_user.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.id
     *
     * @param id the value for system_user.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.email
     *
     * @return the value of system_user.email
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.email
     *
     * @param email the value for system_user.email
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.social_number
     *
     * @return the value of system_user.social_number
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getSocialNumber() {
        return socialNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.social_number
     *
     * @param socialNumber the value for system_user.social_number
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setSocialNumber(String socialNumber) {
        this.socialNumber = socialNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.username
     *
     * @return the value of system_user.username
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.username
     *
     * @param username the value for system_user.username
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.password
     *
     * @return the value of system_user.password
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.password
     *
     * @param password the value for system_user.password
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.enabled
     *
     * @return the value of system_user.enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.enabled
     *
     * @param enabled the value for system_user.enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.profile
     *
     * @return the value of system_user.profile
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getProfile() {
        return profile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.profile
     *
     * @param profile the value for system_user.profile
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setProfile(Long profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.last_unit_content
     *
     * @return the value of system_user.last_unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getLastUnitContent() {
        return lastUnitContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.last_unit_content
     *
     * @param lastUnitContent the value for system_user.last_unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setLastUnitContent(Long lastUnitContent) {
        this.lastUnitContent = lastUnitContent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.created_at
     *
     * @return the value of system_user.created_at
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.created_at
     *
     * @param createdAt the value for system_user.created_at
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column system_user.authentication
     *
     * @return the value of system_user.authentication
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column system_user.authentication
     *
     * @param authentication the value for system_user.authentication
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setAuthentication(Long authentication) {
        this.authentication = authentication;
    }
}