package org.ivela.offline.domain;

import java.math.BigDecimal;

public class Transcript {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.grade
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long grade;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long systemUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.status
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal score;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.average_exercise
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal averageExercise;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.average_exam
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal averageExam;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.manual_score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal manualScore;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.challenges_done
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Short challengesDone;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.challenges_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer challengesWeight;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.average_challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal averageChallenge;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column transcript.challenges_total
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private BigDecimal challengesTotal;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.id
     *
     * @return the value of transcript.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.id
     *
     * @param id the value for transcript.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.grade
     *
     * @return the value of transcript.grade
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getGrade() {
        return grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.grade
     *
     * @param grade the value for transcript.grade
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setGrade(Long grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.system_user
     *
     * @return the value of transcript.system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getSystemUser() {
        return systemUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.system_user
     *
     * @param systemUser the value for transcript.system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setSystemUser(Long systemUser) {
        this.systemUser = systemUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.status
     *
     * @return the value of transcript.status
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.status
     *
     * @param status the value for transcript.status
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.score
     *
     * @return the value of transcript.score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.score
     *
     * @param score the value for transcript.score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.average_exercise
     *
     * @return the value of transcript.average_exercise
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getAverageExercise() {
        return averageExercise;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.average_exercise
     *
     * @param averageExercise the value for transcript.average_exercise
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setAverageExercise(BigDecimal averageExercise) {
        this.averageExercise = averageExercise;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.average_exam
     *
     * @return the value of transcript.average_exam
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getAverageExam() {
        return averageExam;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.average_exam
     *
     * @param averageExam the value for transcript.average_exam
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setAverageExam(BigDecimal averageExam) {
        this.averageExam = averageExam;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.manual_score
     *
     * @return the value of transcript.manual_score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getManualScore() {
        return manualScore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.manual_score
     *
     * @param manualScore the value for transcript.manual_score
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setManualScore(BigDecimal manualScore) {
        this.manualScore = manualScore;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.challenges_done
     *
     * @return the value of transcript.challenges_done
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Short getChallengesDone() {
        return challengesDone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.challenges_done
     *
     * @param challengesDone the value for transcript.challenges_done
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengesDone(Short challengesDone) {
        this.challengesDone = challengesDone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.challenges_weight
     *
     * @return the value of transcript.challenges_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getChallengesWeight() {
        return challengesWeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.challenges_weight
     *
     * @param challengesWeight the value for transcript.challenges_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengesWeight(Integer challengesWeight) {
        this.challengesWeight = challengesWeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.average_challenge
     *
     * @return the value of transcript.average_challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getAverageChallenge() {
        return averageChallenge;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.average_challenge
     *
     * @param averageChallenge the value for transcript.average_challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setAverageChallenge(BigDecimal averageChallenge) {
        this.averageChallenge = averageChallenge;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column transcript.challenges_total
     *
     * @return the value of transcript.challenges_total
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public BigDecimal getChallengesTotal() {
        return challengesTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column transcript.challenges_total
     *
     * @param challengesTotal the value for transcript.challenges_total
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengesTotal(BigDecimal challengesTotal) {
        this.challengesTotal = challengesTotal;
    }
}