package org.ivela.offline.domain;

public class Unit {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long discipline;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Boolean active;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit.discipline
     *
     * @return the value of unit.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getDiscipline() {
        return discipline;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit.discipline
     *
     * @param discipline the value for unit.discipline
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDiscipline(Long discipline) {
        this.discipline = discipline;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit.name
     *
     * @return the value of unit.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit.name
     *
     * @param name the value for unit.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit.active
     *
     * @return the value of unit.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit.active
     *
     * @param active the value for unit.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setActive(Boolean active) {
        this.active = active;
    }
}