package org.ivela.offline.domain;

public class Challenge {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.challid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String challid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.challvalue
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Double challvalue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.uid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long uid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.unit_id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer unitId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column challenge.retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Short retries;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.id
     *
     * @return the value of challenge.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.id
     *
     * @param id the value for challenge.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.challid
     *
     * @return the value of challenge.challid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getChallid() {
        return challid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.challid
     *
     * @param challid the value for challenge.challid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallid(String challid) {
        this.challid = challid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.challvalue
     *
     * @return the value of challenge.challvalue
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Double getChallvalue() {
        return challvalue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.challvalue
     *
     * @param challvalue the value for challenge.challvalue
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallvalue(Double challvalue) {
        this.challvalue = challvalue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.uid
     *
     * @return the value of challenge.uid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.uid
     *
     * @param uid the value for challenge.uid
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.unit_id
     *
     * @return the value of challenge.unit_id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.unit_id
     *
     * @param unitId the value for challenge.unit_id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column challenge.retries
     *
     * @return the value of challenge.retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Short getRetries() {
        return retries;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column challenge.retries
     *
     * @param retries the value for challenge.retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setRetries(Short retries) {
        this.retries = retries;
    }
}