package org.ivela.offline.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CourseExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public CourseExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected CourseExample(CourseExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table course
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("description in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("description not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return this;
        }

        public Criteria andImageIn(List values) {
            addCriterion("image in", values, "image");
            return this;
        }

        public Criteria andImageNotIn(List values) {
            addCriterion("image not in", values, "image");
            return this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return this;
        }

        public Criteria andTargetAudienceIsNull() {
            addCriterion("target_audience is null");
            return this;
        }

        public Criteria andTargetAudienceIsNotNull() {
            addCriterion("target_audience is not null");
            return this;
        }

        public Criteria andTargetAudienceEqualTo(String value) {
            addCriterion("target_audience =", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceNotEqualTo(String value) {
            addCriterion("target_audience <>", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceGreaterThan(String value) {
            addCriterion("target_audience >", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceGreaterThanOrEqualTo(String value) {
            addCriterion("target_audience >=", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceLessThan(String value) {
            addCriterion("target_audience <", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceLessThanOrEqualTo(String value) {
            addCriterion("target_audience <=", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceLike(String value) {
            addCriterion("target_audience like", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceNotLike(String value) {
            addCriterion("target_audience not like", value, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceIn(List values) {
            addCriterion("target_audience in", values, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceNotIn(List values) {
            addCriterion("target_audience not in", values, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceBetween(String value1, String value2) {
            addCriterion("target_audience between", value1, value2, "targetAudience");
            return this;
        }

        public Criteria andTargetAudienceNotBetween(String value1, String value2) {
            addCriterion("target_audience not between", value1, value2, "targetAudience");
            return this;
        }

        public Criteria andContentsIsNull() {
            addCriterion("contents is null");
            return this;
        }

        public Criteria andContentsIsNotNull() {
            addCriterion("contents is not null");
            return this;
        }

        public Criteria andContentsEqualTo(String value) {
            addCriterion("contents =", value, "contents");
            return this;
        }

        public Criteria andContentsNotEqualTo(String value) {
            addCriterion("contents <>", value, "contents");
            return this;
        }

        public Criteria andContentsGreaterThan(String value) {
            addCriterion("contents >", value, "contents");
            return this;
        }

        public Criteria andContentsGreaterThanOrEqualTo(String value) {
            addCriterion("contents >=", value, "contents");
            return this;
        }

        public Criteria andContentsLessThan(String value) {
            addCriterion("contents <", value, "contents");
            return this;
        }

        public Criteria andContentsLessThanOrEqualTo(String value) {
            addCriterion("contents <=", value, "contents");
            return this;
        }

        public Criteria andContentsLike(String value) {
            addCriterion("contents like", value, "contents");
            return this;
        }

        public Criteria andContentsNotLike(String value) {
            addCriterion("contents not like", value, "contents");
            return this;
        }

        public Criteria andContentsIn(List values) {
            addCriterion("contents in", values, "contents");
            return this;
        }

        public Criteria andContentsNotIn(List values) {
            addCriterion("contents not in", values, "contents");
            return this;
        }

        public Criteria andContentsBetween(String value1, String value2) {
            addCriterion("contents between", value1, value2, "contents");
            return this;
        }

        public Criteria andContentsNotBetween(String value1, String value2) {
            addCriterion("contents not between", value1, value2, "contents");
            return this;
        }

        public Criteria andRepositoryStructureIsNull() {
            addCriterion("repository_structure is null");
            return this;
        }

        public Criteria andRepositoryStructureIsNotNull() {
            addCriterion("repository_structure is not null");
            return this;
        }

        public Criteria andRepositoryStructureEqualTo(String value) {
            addCriterion("repository_structure =", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureNotEqualTo(String value) {
            addCriterion("repository_structure <>", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureGreaterThan(String value) {
            addCriterion("repository_structure >", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureGreaterThanOrEqualTo(String value) {
            addCriterion("repository_structure >=", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureLessThan(String value) {
            addCriterion("repository_structure <", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureLessThanOrEqualTo(String value) {
            addCriterion("repository_structure <=", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureLike(String value) {
            addCriterion("repository_structure like", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureNotLike(String value) {
            addCriterion("repository_structure not like", value, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureIn(List values) {
            addCriterion("repository_structure in", values, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureNotIn(List values) {
            addCriterion("repository_structure not in", values, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureBetween(String value1, String value2) {
            addCriterion("repository_structure between", value1, value2, "repositoryStructure");
            return this;
        }

        public Criteria andRepositoryStructureNotBetween(String value1, String value2) {
            addCriterion("repository_structure not between", value1, value2, "repositoryStructure");
            return this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("active is null");
            return this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("active is not null");
            return this;
        }

        public Criteria andActiveEqualTo(Boolean value) {
            addCriterion("active =", value, "active");
            return this;
        }

        public Criteria andActiveNotEqualTo(Boolean value) {
            addCriterion("active <>", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThan(Boolean value) {
            addCriterion("active >", value, "active");
            return this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("active >=", value, "active");
            return this;
        }

        public Criteria andActiveLessThan(Boolean value) {
            addCriterion("active <", value, "active");
            return this;
        }

        public Criteria andActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("active <=", value, "active");
            return this;
        }

        public Criteria andActiveIn(List values) {
            addCriterion("active in", values, "active");
            return this;
        }

        public Criteria andActiveNotIn(List values) {
            addCriterion("active not in", values, "active");
            return this;
        }

        public Criteria andActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("active between", value1, value2, "active");
            return this;
        }

        public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("active not between", value1, value2, "active");
            return this;
        }

        public Criteria andUploadPackageEnabledIsNull() {
            addCriterion("upload_package_enabled is null");
            return this;
        }

        public Criteria andUploadPackageEnabledIsNotNull() {
            addCriterion("upload_package_enabled is not null");
            return this;
        }

        public Criteria andUploadPackageEnabledEqualTo(Boolean value) {
            addCriterion("upload_package_enabled =", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledNotEqualTo(Boolean value) {
            addCriterion("upload_package_enabled <>", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledGreaterThan(Boolean value) {
            addCriterion("upload_package_enabled >", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("upload_package_enabled >=", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledLessThan(Boolean value) {
            addCriterion("upload_package_enabled <", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("upload_package_enabled <=", value, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledIn(List values) {
            addCriterion("upload_package_enabled in", values, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledNotIn(List values) {
            addCriterion("upload_package_enabled not in", values, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("upload_package_enabled between", value1, value2, "uploadPackageEnabled");
            return this;
        }

        public Criteria andUploadPackageEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("upload_package_enabled not between", value1, value2, "uploadPackageEnabled");
            return this;
        }

        public Criteria andCustomTocIsNull() {
            addCriterion("custom_toc is null");
            return this;
        }

        public Criteria andCustomTocIsNotNull() {
            addCriterion("custom_toc is not null");
            return this;
        }

        public Criteria andCustomTocEqualTo(Boolean value) {
            addCriterion("custom_toc =", value, "customToc");
            return this;
        }

        public Criteria andCustomTocNotEqualTo(Boolean value) {
            addCriterion("custom_toc <>", value, "customToc");
            return this;
        }

        public Criteria andCustomTocGreaterThan(Boolean value) {
            addCriterion("custom_toc >", value, "customToc");
            return this;
        }

        public Criteria andCustomTocGreaterThanOrEqualTo(Boolean value) {
            addCriterion("custom_toc >=", value, "customToc");
            return this;
        }

        public Criteria andCustomTocLessThan(Boolean value) {
            addCriterion("custom_toc <", value, "customToc");
            return this;
        }

        public Criteria andCustomTocLessThanOrEqualTo(Boolean value) {
            addCriterion("custom_toc <=", value, "customToc");
            return this;
        }

        public Criteria andCustomTocIn(List values) {
            addCriterion("custom_toc in", values, "customToc");
            return this;
        }

        public Criteria andCustomTocNotIn(List values) {
            addCriterion("custom_toc not in", values, "customToc");
            return this;
        }

        public Criteria andCustomTocBetween(Boolean value1, Boolean value2) {
            addCriterion("custom_toc between", value1, value2, "customToc");
            return this;
        }

        public Criteria andCustomTocNotBetween(Boolean value1, Boolean value2) {
            addCriterion("custom_toc not between", value1, value2, "customToc");
            return this;
        }

        public Criteria andChallengeRetriesIsNull() {
            addCriterion("challenge_retries is null");
            return this;
        }

        public Criteria andChallengeRetriesIsNotNull() {
            addCriterion("challenge_retries is not null");
            return this;
        }

        public Criteria andChallengeRetriesEqualTo(Short value) {
            addCriterion("challenge_retries =", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesNotEqualTo(Short value) {
            addCriterion("challenge_retries <>", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesGreaterThan(Short value) {
            addCriterion("challenge_retries >", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesGreaterThanOrEqualTo(Short value) {
            addCriterion("challenge_retries >=", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesLessThan(Short value) {
            addCriterion("challenge_retries <", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesLessThanOrEqualTo(Short value) {
            addCriterion("challenge_retries <=", value, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesIn(List values) {
            addCriterion("challenge_retries in", values, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesNotIn(List values) {
            addCriterion("challenge_retries not in", values, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesBetween(Short value1, Short value2) {
            addCriterion("challenge_retries between", value1, value2, "challengeRetries");
            return this;
        }

        public Criteria andChallengeRetriesNotBetween(Short value1, Short value2) {
            addCriterion("challenge_retries not between", value1, value2, "challengeRetries");
            return this;
        }

        public Criteria andChallengeCountIsNull() {
            addCriterion("challenge_count is null");
            return this;
        }

        public Criteria andChallengeCountIsNotNull() {
            addCriterion("challenge_count is not null");
            return this;
        }

        public Criteria andChallengeCountEqualTo(Short value) {
            addCriterion("challenge_count =", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountNotEqualTo(Short value) {
            addCriterion("challenge_count <>", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountGreaterThan(Short value) {
            addCriterion("challenge_count >", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountGreaterThanOrEqualTo(Short value) {
            addCriterion("challenge_count >=", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountLessThan(Short value) {
            addCriterion("challenge_count <", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountLessThanOrEqualTo(Short value) {
            addCriterion("challenge_count <=", value, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountIn(List values) {
            addCriterion("challenge_count in", values, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountNotIn(List values) {
            addCriterion("challenge_count not in", values, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountBetween(Short value1, Short value2) {
            addCriterion("challenge_count between", value1, value2, "challengeCount");
            return this;
        }

        public Criteria andChallengeCountNotBetween(Short value1, Short value2) {
            addCriterion("challenge_count not between", value1, value2, "challengeCount");
            return this;
        }

        public Criteria andChallengeWeightIsNull() {
            addCriterion("challenge_weight is null");
            return this;
        }

        public Criteria andChallengeWeightIsNotNull() {
            addCriterion("challenge_weight is not null");
            return this;
        }

        public Criteria andChallengeWeightEqualTo(Integer value) {
            addCriterion("challenge_weight =", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightNotEqualTo(Integer value) {
            addCriterion("challenge_weight <>", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightGreaterThan(Integer value) {
            addCriterion("challenge_weight >", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("challenge_weight >=", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightLessThan(Integer value) {
            addCriterion("challenge_weight <", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightLessThanOrEqualTo(Integer value) {
            addCriterion("challenge_weight <=", value, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightIn(List values) {
            addCriterion("challenge_weight in", values, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightNotIn(List values) {
            addCriterion("challenge_weight not in", values, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightBetween(Integer value1, Integer value2) {
            addCriterion("challenge_weight between", value1, value2, "challengeWeight");
            return this;
        }

        public Criteria andChallengeWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("challenge_weight not between", value1, value2, "challengeWeight");
            return this;
        }
    }
}