package org.ivela.offline.domain;

public class Course {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.image
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String image;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.target_audience
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String targetAudience;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.contents
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String contents;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.repository_structure
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String repositoryStructure;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Boolean active;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.upload_package_enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Boolean uploadPackageEnabled;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.custom_toc
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Boolean customToc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.challenge_retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Short challengeRetries;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.challenge_count
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Short challengeCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column course.challenge_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer challengeWeight;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.image
     *
     * @return the value of course.image
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.image
     *
     * @param image the value for course.image
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.target_audience
     *
     * @return the value of course.target_audience
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getTargetAudience() {
        return targetAudience;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.target_audience
     *
     * @param targetAudience the value for course.target_audience
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setTargetAudience(String targetAudience) {
        this.targetAudience = targetAudience;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.contents
     *
     * @return the value of course.contents
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.contents
     *
     * @param contents the value for course.contents
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.repository_structure
     *
     * @return the value of course.repository_structure
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getRepositoryStructure() {
        return repositoryStructure;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.repository_structure
     *
     * @param repositoryStructure the value for course.repository_structure
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setRepositoryStructure(String repositoryStructure) {
        this.repositoryStructure = repositoryStructure;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.active
     *
     * @return the value of course.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.active
     *
     * @param active the value for course.active
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.upload_package_enabled
     *
     * @return the value of course.upload_package_enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Boolean getUploadPackageEnabled() {
        return uploadPackageEnabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.upload_package_enabled
     *
     * @param uploadPackageEnabled the value for course.upload_package_enabled
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUploadPackageEnabled(Boolean uploadPackageEnabled) {
        this.uploadPackageEnabled = uploadPackageEnabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.custom_toc
     *
     * @return the value of course.custom_toc
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Boolean getCustomToc() {
        return customToc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.custom_toc
     *
     * @param customToc the value for course.custom_toc
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setCustomToc(Boolean customToc) {
        this.customToc = customToc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.challenge_retries
     *
     * @return the value of course.challenge_retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Short getChallengeRetries() {
        return challengeRetries;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.challenge_retries
     *
     * @param challengeRetries the value for course.challenge_retries
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengeRetries(Short challengeRetries) {
        this.challengeRetries = challengeRetries;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.challenge_count
     *
     * @return the value of course.challenge_count
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Short getChallengeCount() {
        return challengeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.challenge_count
     *
     * @param challengeCount the value for course.challenge_count
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengeCount(Short challengeCount) {
        this.challengeCount = challengeCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column course.challenge_weight
     *
     * @return the value of course.challenge_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getChallengeWeight() {
        return challengeWeight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column course.challenge_weight
     *
     * @param challengeWeight the value for course.challenge_weight
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setChallengeWeight(Integer challengeWeight) {
        this.challengeWeight = challengeWeight;
    }
}