package org.ivela.offline.domain;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SystemUserExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public SystemUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected SystemUserExample(SystemUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table system_user
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andSocialNumberIsNull() {
            addCriterion("social_number is null");
            return this;
        }

        public Criteria andSocialNumberIsNotNull() {
            addCriterion("social_number is not null");
            return this;
        }

        public Criteria andSocialNumberEqualTo(String value) {
            addCriterion("social_number =", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberNotEqualTo(String value) {
            addCriterion("social_number <>", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberGreaterThan(String value) {
            addCriterion("social_number >", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberGreaterThanOrEqualTo(String value) {
            addCriterion("social_number >=", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberLessThan(String value) {
            addCriterion("social_number <", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberLessThanOrEqualTo(String value) {
            addCriterion("social_number <=", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberLike(String value) {
            addCriterion("social_number like", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberNotLike(String value) {
            addCriterion("social_number not like", value, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberIn(List values) {
            addCriterion("social_number in", values, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberNotIn(List values) {
            addCriterion("social_number not in", values, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberBetween(String value1, String value2) {
            addCriterion("social_number between", value1, value2, "socialNumber");
            return this;
        }

        public Criteria andSocialNumberNotBetween(String value1, String value2) {
            addCriterion("social_number not between", value1, value2, "socialNumber");
            return this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List values) {
            addCriterion("username in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List values) {
            addCriterion("username not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return this;
        }

        public Criteria andEnabledIn(List values) {
            addCriterion("enabled in", values, "enabled");
            return this;
        }

        public Criteria andEnabledNotIn(List values) {
            addCriterion("enabled not in", values, "enabled");
            return this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return this;
        }

        public Criteria andProfileIsNull() {
            addCriterion("profile is null");
            return this;
        }

        public Criteria andProfileIsNotNull() {
            addCriterion("profile is not null");
            return this;
        }

        public Criteria andProfileEqualTo(Long value) {
            addCriterion("profile =", value, "profile");
            return this;
        }

        public Criteria andProfileNotEqualTo(Long value) {
            addCriterion("profile <>", value, "profile");
            return this;
        }

        public Criteria andProfileGreaterThan(Long value) {
            addCriterion("profile >", value, "profile");
            return this;
        }

        public Criteria andProfileGreaterThanOrEqualTo(Long value) {
            addCriterion("profile >=", value, "profile");
            return this;
        }

        public Criteria andProfileLessThan(Long value) {
            addCriterion("profile <", value, "profile");
            return this;
        }

        public Criteria andProfileLessThanOrEqualTo(Long value) {
            addCriterion("profile <=", value, "profile");
            return this;
        }

        public Criteria andProfileIn(List values) {
            addCriterion("profile in", values, "profile");
            return this;
        }

        public Criteria andProfileNotIn(List values) {
            addCriterion("profile not in", values, "profile");
            return this;
        }

        public Criteria andProfileBetween(Long value1, Long value2) {
            addCriterion("profile between", value1, value2, "profile");
            return this;
        }

        public Criteria andProfileNotBetween(Long value1, Long value2) {
            addCriterion("profile not between", value1, value2, "profile");
            return this;
        }

        public Criteria andLastUnitContentIsNull() {
            addCriterion("last_unit_content is null");
            return this;
        }

        public Criteria andLastUnitContentIsNotNull() {
            addCriterion("last_unit_content is not null");
            return this;
        }

        public Criteria andLastUnitContentEqualTo(Long value) {
            addCriterion("last_unit_content =", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentNotEqualTo(Long value) {
            addCriterion("last_unit_content <>", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentGreaterThan(Long value) {
            addCriterion("last_unit_content >", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentGreaterThanOrEqualTo(Long value) {
            addCriterion("last_unit_content >=", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentLessThan(Long value) {
            addCriterion("last_unit_content <", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentLessThanOrEqualTo(Long value) {
            addCriterion("last_unit_content <=", value, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentIn(List values) {
            addCriterion("last_unit_content in", values, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentNotIn(List values) {
            addCriterion("last_unit_content not in", values, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentBetween(Long value1, Long value2) {
            addCriterion("last_unit_content between", value1, value2, "lastUnitContent");
            return this;
        }

        public Criteria andLastUnitContentNotBetween(Long value1, Long value2) {
            addCriterion("last_unit_content not between", value1, value2, "lastUnitContent");
            return this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtIn(List values) {
            addCriterion("created_at in", values, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotIn(List values) {
            addCriterion("created_at not in", values, "createdAt");
            return this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return this;
        }

        public Criteria andAuthenticationIsNull() {
            addCriterion("authentication is null");
            return this;
        }

        public Criteria andAuthenticationIsNotNull() {
            addCriterion("authentication is not null");
            return this;
        }

        public Criteria andAuthenticationEqualTo(Long value) {
            addCriterion("authentication =", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationNotEqualTo(Long value) {
            addCriterion("authentication <>", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationGreaterThan(Long value) {
            addCriterion("authentication >", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationGreaterThanOrEqualTo(Long value) {
            addCriterion("authentication >=", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationLessThan(Long value) {
            addCriterion("authentication <", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationLessThanOrEqualTo(Long value) {
            addCriterion("authentication <=", value, "authentication");
            return this;
        }

        public Criteria andAuthenticationIn(List values) {
            addCriterion("authentication in", values, "authentication");
            return this;
        }

        public Criteria andAuthenticationNotIn(List values) {
            addCriterion("authentication not in", values, "authentication");
            return this;
        }

        public Criteria andAuthenticationBetween(Long value1, Long value2) {
            addCriterion("authentication between", value1, value2, "authentication");
            return this;
        }

        public Criteria andAuthenticationNotBetween(Long value1, Long value2) {
            addCriterion("authentication not between", value1, value2, "authentication");
            return this;
        }
    }
}