package org.ivela.offline.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class UnitContentExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public UnitContentExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected UnitContentExample(UnitContentExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table unit_content
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List timeList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andOrderNIsNull() {
            addCriterion("order_n is null");
            return this;
        }

        public Criteria andOrderNIsNotNull() {
            addCriterion("order_n is not null");
            return this;
        }

        public Criteria andOrderNEqualTo(Integer value) {
            addCriterion("order_n =", value, "orderN");
            return this;
        }

        public Criteria andOrderNNotEqualTo(Integer value) {
            addCriterion("order_n <>", value, "orderN");
            return this;
        }

        public Criteria andOrderNGreaterThan(Integer value) {
            addCriterion("order_n >", value, "orderN");
            return this;
        }

        public Criteria andOrderNGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_n >=", value, "orderN");
            return this;
        }

        public Criteria andOrderNLessThan(Integer value) {
            addCriterion("order_n <", value, "orderN");
            return this;
        }

        public Criteria andOrderNLessThanOrEqualTo(Integer value) {
            addCriterion("order_n <=", value, "orderN");
            return this;
        }

        public Criteria andOrderNIn(List values) {
            addCriterion("order_n in", values, "orderN");
            return this;
        }

        public Criteria andOrderNNotIn(List values) {
            addCriterion("order_n not in", values, "orderN");
            return this;
        }

        public Criteria andOrderNBetween(Integer value1, Integer value2) {
            addCriterion("order_n between", value1, value2, "orderN");
            return this;
        }

        public Criteria andOrderNNotBetween(Integer value1, Integer value2) {
            addCriterion("order_n not between", value1, value2, "orderN");
            return this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return this;
        }

        public Criteria andUnitEqualTo(Long value) {
            addCriterion("unit =", value, "unit");
            return this;
        }

        public Criteria andUnitNotEqualTo(Long value) {
            addCriterion("unit <>", value, "unit");
            return this;
        }

        public Criteria andUnitGreaterThan(Long value) {
            addCriterion("unit >", value, "unit");
            return this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(Long value) {
            addCriterion("unit >=", value, "unit");
            return this;
        }

        public Criteria andUnitLessThan(Long value) {
            addCriterion("unit <", value, "unit");
            return this;
        }

        public Criteria andUnitLessThanOrEqualTo(Long value) {
            addCriterion("unit <=", value, "unit");
            return this;
        }

        public Criteria andUnitIn(List values) {
            addCriterion("unit in", values, "unit");
            return this;
        }

        public Criteria andUnitNotIn(List values) {
            addCriterion("unit not in", values, "unit");
            return this;
        }

        public Criteria andUnitBetween(Long value1, Long value2) {
            addCriterion("unit between", value1, value2, "unit");
            return this;
        }

        public Criteria andUnitNotBetween(Long value1, Long value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("description in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("description not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return this;
        }

        public Criteria andWidthIn(List values) {
            addCriterion("width in", values, "width");
            return this;
        }

        public Criteria andWidthNotIn(List values) {
            addCriterion("width not in", values, "width");
            return this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return this;
        }

        public Criteria andHeightEqualTo(Integer value) {
            addCriterion("height =", value, "height");
            return this;
        }

        public Criteria andHeightNotEqualTo(Integer value) {
            addCriterion("height <>", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThan(Integer value) {
            addCriterion("height >", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("height >=", value, "height");
            return this;
        }

        public Criteria andHeightLessThan(Integer value) {
            addCriterion("height <", value, "height");
            return this;
        }

        public Criteria andHeightLessThanOrEqualTo(Integer value) {
            addCriterion("height <=", value, "height");
            return this;
        }

        public Criteria andHeightIn(List values) {
            addCriterion("height in", values, "height");
            return this;
        }

        public Criteria andHeightNotIn(List values) {
            addCriterion("height not in", values, "height");
            return this;
        }

        public Criteria andHeightBetween(Integer value1, Integer value2) {
            addCriterion("height between", value1, value2, "height");
            return this;
        }

        public Criteria andHeightNotBetween(Integer value1, Integer value2) {
            addCriterion("height not between", value1, value2, "height");
            return this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return this;
        }

        public Criteria andDurationEqualTo(Date value) {
            addCriterionForJDBCTime("duration =", value, "duration");
            return this;
        }

        public Criteria andDurationNotEqualTo(Date value) {
            addCriterionForJDBCTime("duration <>", value, "duration");
            return this;
        }

        public Criteria andDurationGreaterThan(Date value) {
            addCriterionForJDBCTime("duration >", value, "duration");
            return this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("duration >=", value, "duration");
            return this;
        }

        public Criteria andDurationLessThan(Date value) {
            addCriterionForJDBCTime("duration <", value, "duration");
            return this;
        }

        public Criteria andDurationLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("duration <=", value, "duration");
            return this;
        }

        public Criteria andDurationIn(List values) {
            addCriterionForJDBCTime("duration in", values, "duration");
            return this;
        }

        public Criteria andDurationNotIn(List values) {
            addCriterionForJDBCTime("duration not in", values, "duration");
            return this;
        }

        public Criteria andDurationBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("duration between", value1, value2, "duration");
            return this;
        }

        public Criteria andDurationNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("duration not between", value1, value2, "duration");
            return this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return this;
        }

        public Criteria andTagIn(List values) {
            addCriterion("tag in", values, "tag");
            return this;
        }

        public Criteria andTagNotIn(List values) {
            addCriterion("tag not in", values, "tag");
            return this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return this;
        }
    }
}