package org.ivela.offline.domain;

import java.util.Date;

public class UnitContent {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.order_n
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer orderN;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Long unit;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.title
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.type
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.width
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer width;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.height
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Integer height;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.duration
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private Date duration;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column unit_content.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    private String tag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.id
     *
     * @return the value of unit_content.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.id
     *
     * @param id the value for unit_content.id
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.order_n
     *
     * @return the value of unit_content.order_n
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getOrderN() {
        return orderN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.order_n
     *
     * @param orderN the value for unit_content.order_n
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setOrderN(Integer orderN) {
        this.orderN = orderN;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.unit
     *
     * @return the value of unit_content.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Long getUnit() {
        return unit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.unit
     *
     * @param unit the value for unit_content.unit
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setUnit(Long unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.title
     *
     * @return the value of unit_content.title
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.title
     *
     * @param title the value for unit_content.title
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.description
     *
     * @return the value of unit_content.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.description
     *
     * @param description the value for unit_content.description
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.type
     *
     * @return the value of unit_content.type
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.type
     *
     * @param type the value for unit_content.type
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.width
     *
     * @return the value of unit_content.width
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.width
     *
     * @param width the value for unit_content.width
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.height
     *
     * @return the value of unit_content.height
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.height
     *
     * @param height the value for unit_content.height
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.duration
     *
     * @return the value of unit_content.duration
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public Date getDuration() {
        return duration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.duration
     *
     * @param duration the value for unit_content.duration
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setDuration(Date duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column unit_content.tag
     *
     * @return the value of unit_content.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column unit_content.tag
     *
     * @param tag the value for unit_content.tag
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}