package org.ivela.offline.dao;

import java.sql.SQLException;
import java.util.List;

import org.ivela.offline.domain.Challenge;
import org.ivela.offline.domain.ChallengeExample;

public interface ChallengeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int countByExample(ChallengeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int deleteByExample(ChallengeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int deleteByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    void insert(Challenge record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    void insertSelective(Challenge record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    List selectByExample(ChallengeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    Challenge selectByPrimaryKey(Long id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByExampleSelective(Challenge record, ChallengeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByExample(Challenge record, ChallengeExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByPrimaryKeySelective(Challenge record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table challenge
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByPrimaryKey(Challenge record) throws SQLException;
}