package org.ivela.offline.dao;

import java.sql.SQLException;
import java.util.List;

import org.ivela.offline.domain.Transcript;
import org.ivela.offline.domain.TranscriptExample;

public interface TranscriptDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int countByExample(TranscriptExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int deleteByExample(TranscriptExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    void insert(Transcript record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    void insertSelective(Transcript record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    List selectByExample(TranscriptExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    Transcript selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByExampleSelective(Transcript record, TranscriptExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByExample(Transcript record, TranscriptExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByPrimaryKeySelective(Transcript record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table transcript
     *
     * @ibatorgenerated Thu Apr 15 14:20:41 BRT 2010
     */
    int updateByPrimaryKey(Transcript record) throws SQLException;
}